menu:
  首页: /
  关于: /about
  归档: archives
  RSS订阅: /atom.xml

widgets:
- about_me
- calendar
- category
- tagcloud
- recent_posts
- links
- duoshuo_recent_comments

highlightjs: monokai_sublime

excerpt_link: 阅读全文

twitter_id: wileam
facebook_id: Joanna.Wu.0326
github_id: wileam

addthis:
 # enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-41666896-1
rss: /atom.xml

links:
- name: 个人主页
  link: http://www.wileam.com
- name: 技术博客
  link: http://code.wileam.com

duoshuo: wileamblog

about_me:
  title: 关于我
  avatar: /uploads/avatar.jpg
  texts:
  - <a href="/about" target="_BLANK">Joanna Wu(wileam)</a>
  - Smile, breathe & go slowly. ^_^
  - <br>
  - <img src="/uploads/email.gif">
